# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16object_detection.proto\x12\x10object_detection\"\x1b\n\x05\x46rame\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\"\x16\n\x06\x42\x42oxes\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32I\n\x08\x44\x65tector\x12=\n\x06\x64\x65tect\x12\x17.object_detection.Frame\x1a\x18.object_detection.BBoxes\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAME']._serialized_start=44
  _globals['_FRAME']._serialized_end=71
  _globals['_BBOXES']._serialized_start=73
  _globals['_BBOXES']._serialized_end=95
  _globals['_DETECTOR']._serialized_start=97
  _globals['_DETECTOR']._serialized_end=170
# @@protoc_insertion_point(module_scope)
